#!/usr/bin/env bash
# A script that run nginx on port 80 and service (init) must say that nginx is not running
sed-i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
pkill -o nginx
