#!/usr/bin/env bash
# script that display "Best School" 10 tiimes but on 9th iteration display "Best School" and "Hi"

b=0
while ((b < 10))
do
	if ((b == 9))
	then
		echo "Hi"
	fi
	echo "Best School"
	((b++))
done
