#!/usr/bin/env bash
# script that loop from 1 to 10 and display:
# "bad luck" on 4th iteration.
# "good luck" on 8th iteration.
# "Best School" for other iteration.

b=1
while ((b <= 10))
do
	if ((b == 4))
	then
		echo "bad luck"
	elif ((b == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((b++))
done
