#!/usr/bin/env bash
# Bash script that loops from 1 to 10 using while and :-
# Display "bad luck" at 4th iteration.
# Display "good luck" at 8th iteration
# Display "Best School" for the rest of iteration.

b=1
while ((b <= 10))
do
	if ((b == 4))
	then
		echo "bad luck"
	elif ((b == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((b++))
done
