#!/usr/bin/env bash
# Script that displays number from 1 to 20 and:
# Displays 4 and then "bad luck" from China for the 4th iteration.
# Displays 9 and then "bad luck" from Japan for the 9th iteration.
# Displays 17 and then "bad luck" from Italy for the 17th iteration.

b=1
while ((b <= 20))
do
	echo $b

	case $b in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((b++))
done
