#!/usr/bin/env bash
# A script that configure a firewall on web server to allow incomming trafic on the following tcp ports:
#22 (SSH)
#443 (HTTPS SSL)
#80 (HTTP)

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
