#!/usr/bin/env bash
# A script that configure the folling requirements:
# nginx running as nginx user
# nginx listening on all active IPs on port 8080

# Change user to nginx
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the ownership and group of the directory
chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /var/log/nginx /var/www/html

# Change listening port to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# Test the configuration
nginx -t

# kill aoache2 process if runing on port 8080
pkill apache2

service nginx restart
