#!/usr/bin/env bash
# A script that configure the folling requirements:
# nginx running as nginx user
# nginx listening on all active IPs on port 8080

# Change user to nginx
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the permission of /etc/nginx/nginx.conf directory
chmod 644 /etc/nginx/nginx.conf

# Change listening port to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# Test the configuration
nginx -t

# kill apache2 process if runing on port 8080
pkill apache2

sudo -u nginx service nginx start
