#!/usr/bin/env bash
# A script that configure nginx running as nginx user and nginx listening on all active IPs on port 8080
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
